package model;
// Generated 15-feb-2018 17:54:17 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private String dnialumno;
     private Grupo grupo;
     private String nombre;
     private String apellidos;
     private Date fechnac;
     private String nacionalidad;
     private String email;
     private Date fechaingreso;
     private int telefonopersonal;
     private String direccion;
     private Integer codpostal;
     private int telefonofijo;
     private String nombrefamiliar;
     private String apellidofamiliar;
     private Integer telefonofamiliar;
     private String emailfamiliar;
     private Set matriculas = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(String dnialumno, Grupo grupo, String nombre, String apellidos, Date fechnac, Date fechaingreso, int telefonopersonal, int telefonofijo) {
        this.dnialumno = dnialumno;
        this.grupo = grupo;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.fechnac = fechnac;
        this.fechaingreso = fechaingreso;
        this.telefonopersonal = telefonopersonal;
        this.telefonofijo = telefonofijo;
    }
    public Alumno(String dnialumno, Grupo grupo, String nombre, String apellidos, Date fechnac, String nacionalidad, String email, Date fechaingreso, int telefonopersonal, String direccion, Integer codpostal, int telefonofijo, String nombrefamiliar, String apellidofamiliar, Integer telefonofamiliar, String emailfamiliar, Set matriculas) {
       this.dnialumno = dnialumno;
       this.grupo = grupo;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.fechnac = fechnac;
       this.nacionalidad = nacionalidad;
       this.email = email;
       this.fechaingreso = fechaingreso;
       this.telefonopersonal = telefonopersonal;
       this.direccion = direccion;
       this.codpostal = codpostal;
       this.telefonofijo = telefonofijo;
       this.nombrefamiliar = nombrefamiliar;
       this.apellidofamiliar = apellidofamiliar;
       this.telefonofamiliar = telefonofamiliar;
       this.emailfamiliar = emailfamiliar;
       this.matriculas = matriculas;
    }
   
    public String getDnialumno() {
        return this.dnialumno;
    }
    
    public void setDnialumno(String dnialumno) {
        this.dnialumno = dnialumno;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Date getFechnac() {
        return this.fechnac;
    }
    
    public void setFechnac(Date fechnac) {
        this.fechnac = fechnac;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFechaingreso() {
        return this.fechaingreso;
    }
    
    public void setFechaingreso(Date fechaingreso) {
        this.fechaingreso = fechaingreso;
    }
    public int getTelefonopersonal() {
        return this.telefonopersonal;
    }
    
    public void setTelefonopersonal(int telefonopersonal) {
        this.telefonopersonal = telefonopersonal;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getCodpostal() {
        return this.codpostal;
    }
    
    public void setCodpostal(Integer codpostal) {
        this.codpostal = codpostal;
    }
    public int getTelefonofijo() {
        return this.telefonofijo;
    }
    
    public void setTelefonofijo(int telefonofijo) {
        this.telefonofijo = telefonofijo;
    }
    public String getNombrefamiliar() {
        return this.nombrefamiliar;
    }
    
    public void setNombrefamiliar(String nombrefamiliar) {
        this.nombrefamiliar = nombrefamiliar;
    }
    public String getApellidofamiliar() {
        return this.apellidofamiliar;
    }
    
    public void setApellidofamiliar(String apellidofamiliar) {
        this.apellidofamiliar = apellidofamiliar;
    }
    public Integer getTelefonofamiliar() {
        return this.telefonofamiliar;
    }
    
    public void setTelefonofamiliar(Integer telefonofamiliar) {
        this.telefonofamiliar = telefonofamiliar;
    }
    public String getEmailfamiliar() {
        return this.emailfamiliar;
    }
    
    public void setEmailfamiliar(String emailfamiliar) {
        this.emailfamiliar = emailfamiliar;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }




}


