package model;
// Generated 15-feb-2018 17:54:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clase generated by hbm2java
 */
public class Clase  implements java.io.Serializable {


     private Integer idClase;
     private Integer capacidad;
     private String nombreclase;
     private Set grupos = new HashSet(0);

    public Clase() {
    }

    public Clase(Integer capacidad, String nombreclase, Set grupos) {
       this.capacidad = capacidad;
       this.nombreclase = nombreclase;
       this.grupos = grupos;
    }
   
    public Integer getIdClase() {
        return this.idClase;
    }
    
    public void setIdClase(Integer idClase) {
        this.idClase = idClase;
    }
    public Integer getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(Integer capacidad) {
        this.capacidad = capacidad;
    }
    public String getNombreclase() {
        return this.nombreclase;
    }
    
    public void setNombreclase(String nombreclase) {
        this.nombreclase = nombreclase;
    }
    public Set getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Set grupos) {
        this.grupos = grupos;
    }




}


