package model;
// Generated 15-feb-2018 17:54:17 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Gastos generated by hbm2java
 */
public class Gastos  implements java.io.Serializable {


     private Integer idGastos;
     private float importe;
     private Date fecha;
     private String concepto;
     private String descripcion;
     private String formapago;

    public Gastos() {
    }

	
    public Gastos(float importe, Date fecha, String concepto) {
        this.importe = importe;
        this.fecha = fecha;
        this.concepto = concepto;
    }
    public Gastos(float importe, Date fecha, String concepto, String descripcion, String formapago) {
       this.importe = importe;
       this.fecha = fecha;
       this.concepto = concepto;
       this.descripcion = descripcion;
       this.formapago = formapago;
    }
   
    public Integer getIdGastos() {
        return this.idGastos;
    }
    
    public void setIdGastos(Integer idGastos) {
        this.idGastos = idGastos;
    }
    public float getImporte() {
        return this.importe;
    }
    
    public void setImporte(float importe) {
        this.importe = importe;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getFormapago() {
        return this.formapago;
    }
    
    public void setFormapago(String formapago) {
        this.formapago = formapago;
    }




}


