package model;
// Generated 15-feb-2018 17:54:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private Integer idGrupo;
     private Clase clase;
     private Personal personal;
     private String nombre;
     private String nivel;
     private Set alumnos = new HashSet(0);

    public Grupo() {
    }

	
    public Grupo(Clase clase, Personal personal, String nombre, String nivel) {
        this.clase = clase;
        this.personal = personal;
        this.nombre = nombre;
        this.nivel = nivel;
    }
    public Grupo(Clase clase, Personal personal, String nombre, String nivel, Set alumnos) {
       this.clase = clase;
       this.personal = personal;
       this.nombre = nombre;
       this.nivel = nivel;
       this.alumnos = alumnos;
    }
   
    public Integer getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(Integer idGrupo) {
        this.idGrupo = idGrupo;
    }
    public Clase getClase() {
        return this.clase;
    }
    
    public void setClase(Clase clase) {
        this.clase = clase;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }




}


