package model;
// Generated 15-feb-2018 17:54:17 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ingresos generated by hbm2java
 */
public class Ingresos  implements java.io.Serializable {


     private Integer idIngresos;
     private float importe;
     private String concepto;
     private Date fecha;
     private String descripcion;
     private String formapago;

    public Ingresos() {
    }

	
    public Ingresos(float importe, String concepto, Date fecha) {
        this.importe = importe;
        this.concepto = concepto;
        this.fecha = fecha;
    }
    public Ingresos(float importe, String concepto, Date fecha, String descripcion, String formapago) {
       this.importe = importe;
       this.concepto = concepto;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.formapago = formapago;
    }
   
    public Integer getIdIngresos() {
        return this.idIngresos;
    }
    
    public void setIdIngresos(Integer idIngresos) {
        this.idIngresos = idIngresos;
    }
    public float getImporte() {
        return this.importe;
    }
    
    public void setImporte(float importe) {
        this.importe = importe;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getFormapago() {
        return this.formapago;
    }
    
    public void setFormapago(String formapago) {
        this.formapago = formapago;
    }




}


