package model;
// Generated 15-feb-2018 17:54:17 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private String dnipersonal;
     private String nombre;
     private String apellidos;
     private Date fechnac;
     private String nacionalidad;
     private String email;
     private String direccion;
     private Integer codpostal;
     private Integer telefonofijo;
     private int telefonopersonal;
     private Integer telefonofamiliar;
     private String tipo;
     private Float sueldo;
     private String cuentabancaria;
     private Set grupos = new HashSet(0);

    public Personal() {
    }

	
    public Personal(String dnipersonal, String nombre, String apellidos, Date fechnac, int telefonopersonal, String cuentabancaria) {
        this.dnipersonal = dnipersonal;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.fechnac = fechnac;
        this.telefonopersonal = telefonopersonal;
        this.cuentabancaria = cuentabancaria;
    }
    public Personal(String dnipersonal, String nombre, String apellidos, Date fechnac, String nacionalidad, String email, String direccion, Integer codpostal, Integer telefonofijo, int telefonopersonal, Integer telefonofamiliar, String tipo, Float sueldo, String cuentabancaria, Set grupos) {
       this.dnipersonal = dnipersonal;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.fechnac = fechnac;
       this.nacionalidad = nacionalidad;
       this.email = email;
       this.direccion = direccion;
       this.codpostal = codpostal;
       this.telefonofijo = telefonofijo;
       this.telefonopersonal = telefonopersonal;
       this.telefonofamiliar = telefonofamiliar;
       this.tipo = tipo;
       this.sueldo = sueldo;
       this.cuentabancaria = cuentabancaria;
       this.grupos = grupos;
    }
   
    public String getDnipersonal() {
        return this.dnipersonal;
    }
    
    public void setDnipersonal(String dnipersonal) {
        this.dnipersonal = dnipersonal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Date getFechnac() {
        return this.fechnac;
    }
    
    public void setFechnac(Date fechnac) {
        this.fechnac = fechnac;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getCodpostal() {
        return this.codpostal;
    }
    
    public void setCodpostal(Integer codpostal) {
        this.codpostal = codpostal;
    }
    public Integer getTelefonofijo() {
        return this.telefonofijo;
    }
    
    public void setTelefonofijo(Integer telefonofijo) {
        this.telefonofijo = telefonofijo;
    }
    public int getTelefonopersonal() {
        return this.telefonopersonal;
    }
    
    public void setTelefonopersonal(int telefonopersonal) {
        this.telefonopersonal = telefonopersonal;
    }
    public Integer getTelefonofamiliar() {
        return this.telefonofamiliar;
    }
    
    public void setTelefonofamiliar(Integer telefonofamiliar) {
        this.telefonofamiliar = telefonofamiliar;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Float getSueldo() {
        return this.sueldo;
    }
    
    public void setSueldo(Float sueldo) {
        this.sueldo = sueldo;
    }
    public String getCuentabancaria() {
        return this.cuentabancaria;
    }
    
    public void setCuentabancaria(String cuentabancaria) {
        this.cuentabancaria = cuentabancaria;
    }
    public Set getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Set grupos) {
        this.grupos = grupos;
    }




}


